export const STRINGS = {
  tabs: {
    practice: 'Practice',
    library: 'Library',
    settings: 'Settings',
  },
  practice: {
    title: 'Practice',
    startPracticeButton: 'Start Practice',
    presetsSectionTitle: 'Session presets',
    streakLabel: 'Current streak',
    streakNoDays: 'No practice yet',
    streakDaysSuffix: 'days',
    streakSingleDaySuffix: 'day',
    presetsBuiltInBadge: 'built-in',
    presetsCustomBadge: 'custom',
    presetContextEdit: 'Edit',
    presetContextRename: 'Rename',
    presetContextDelete: 'Delete',
    presetContextHide: 'Hide',
    presetContextMoveUp: 'Move up',
    presetContextMoveDown: 'Move down',
    preset30SecondGesturesName: '30-Second Gestures',
    preset1MinutePosesName: '1-Minute Poses',
    preset2MinutePosesName: '2-Minute Poses',
    preset5MinuteStudyName: '5-Minute Study',
    presetPortraitPracticeName: 'Portrait Practice',
    presetObjectSketchingName: 'Object Sketching',
  },
  library: {
    title: 'Library',
    openViewerButton: 'Open Viewer',
    searchPlaceholder: 'Search by name or tag...',
    categoryAll: 'All',
    categoryFullBody: 'Full-Body Poses',
    categoryPortraits: 'Portraits',
    categoryPropsObjects: 'Props & Objects',
    categoryHaircuts: 'Haircuts',
    categoryNaturalObjects: 'Natural Objects',
    categoryMuseumObjects: 'Museum Objects',
    categoryAnimals: 'Animals',
    categoryPlaylists: 'Playlists',
    filterGenderLabel: 'Gender',
    filterGenderMale: 'Male',
    filterGenderFemale: 'Female',
    filterDifficultyLabel: 'Difficulty',
    filterDifficultyBeginner: 'Beginner',
    filterDifficultyIntermediate: 'Intermediate',
    filterDifficultyAdvanced: 'Advanced',
    filterFavouritesOnly: 'Favourites only',
    sortLabel: 'Sort',
    sortNewest: 'Newest',
    sortAlphabetical: 'A-Z',
    sortRandom: 'Random',
    startSessionFromSelection: 'Start Session from Selection',
    emptyStateTitle: 'No results',
    emptyStateMessage: 'Try adjusting your filters or search query.',
    quickActionAddFavourite: 'Add to Favourites',
    quickActionRemoveFavourite: 'Remove from Favourites',
    quickActionAddToPlaylist: 'Add to Playlist',
    quickActionPreview: 'Preview',
    quickActionCancel: 'Cancel',
    playlistsEmptyTitle: 'No playlists yet',
    playlistsEmptyMessage: 'Long-press a card and choose "Add to Playlist" to get started.',
    playlistCreateNew: 'Create New Playlist',
    playlistNamePlaceholder: 'Playlist name',
    playlistCreateButton: 'Create',
    playlistCancelButton: 'Cancel',
    playlistRename: 'Rename',
    playlistDelete: 'Delete',
    playlistStartSession: 'Start Session',
    playlistSubjectCount: 'subjects',
    playlistSubjectCountSingular: 'subject',
    playlistRemoveSubject: 'Remove from Playlist',
    playlistDeleteConfirmTitle: 'Delete Playlist',
    playlistDeleteConfirmMessage: 'Are you sure you want to delete this playlist?',
    playlistDeleteConfirmButton: 'Delete',
    playlistSelectTitle: 'Select Playlist',
    playlistAddedToast: 'Added to playlist',
    sessionFromPlaylistLabel: 'From playlist:',
    sessionFromFilterLabel: 'From filtered selection',
    sessionSubjectCountLabel: 'subjects in pool',
  },
  settings: {
    title: 'Settings',
  },
  viewer: {
    title: 'Viewer',
    timerLabel: 'Time remaining',
    play: 'Play',
    pause: 'Pause',
    skip: 'Skip',
    close: 'Close',
    back: 'Back',
    freeStudyTitle: 'Free Study',
    directionalLight: 'Directional light',
    ambientLight: 'Ambient light',
    // Phase 5 display modes
    toolbarToggle: 'Tools',
    modelStyleLabel: 'Model style',
    modelStyleSolid: 'Solid',
    modelStyleMuscle: 'Muscle',
    modelStyleSkeleton: 'Skeleton',
    modelStyleForms: 'Forms',
    modelStyleColouredAnatomy: 'Anatomy',
    wireframeOverlay: 'Wireframe',
    negativeSpaceMode: 'Negative space',
    gridOverlayLabel: 'Grid overlay',
    gridOverlayOff: 'Off',
    gridOverlay4: '4',
    gridOverlay9: '9',
    gridOverlay16: '16',
    showBoundingBox: 'Bounding box',
    showFloorPlane: 'Floor plane',
    showPoseShadow: 'Pose shadow',
    modelOpacityLabel: 'Model opacity',
    mirrorLabel: 'Mirror',
    staticModeLabel: 'Static 2D',
    limbSelectionLabel: 'Body regions',
    regionHead: 'Head',
    regionTorso: 'Torso',
    regionLeftArm: 'L. Arm',
    regionRightArm: 'R. Arm',
    regionLeftLeg: 'L. Leg',
    regionRightLeg: 'R. Leg',
  },
  common: {
    on: 'On',
    off: 'Off',
  },
  sessionConfig: {
    title: 'Session configuration',
    startSessionButton: 'Start session',
    savePresetButton: 'Save as preset',
    savePresetAsNewButton: 'Save as new preset',
    updatePresetButton: 'Update preset',
    presetNameLabel: 'Preset name',
    presetsSectionTitle: 'Saved presets',
    subjectSectionTitle: 'Subject selection',
    displaySectionTitle: 'Display options',
    lightingSectionTitle: 'Lighting options',
    timeSectionTitle: 'Time options',
    categoryLabel: 'Pose categories',
    genderLabel: 'Gender',
    genderMale: 'Male',
    genderFemale: 'Female',
    genderBoth: 'Both',
    showGridLabel: 'Show ground grid',
    backgroundLabel: 'Background',
    backgroundDark: 'Dark',
    backgroundMid: 'Mid',
    backgroundLight: 'Light',
    directionalLightLabel: 'Directional light intensity',
    ambientLightLabel: 'Ambient light intensity',
    poseDurationLabel: 'Pose duration',
    poseCountLabel: 'Number of poses',
    breakDurationLabel: 'Break between poses',
    randomOrderLabel: 'Random order',
    durationSeconds: 'seconds',
    durationMinutes: 'minutes',
    posesSuffix: 'poses',
    breakOff: 'Off',
    breakSecondsSuffix: 's break',
    // Phase 5
    modelStyleLabel: 'Model style',
    wireframeOverlayLabel: 'Wireframe overlay',
    negativeSpaceLabel: 'Negative space mode',
    gridOverlayLabel: 'Grid overlay',
    boundingBoxLabel: 'Bounding box',
    floorPlaneLabel: 'Floor plane',
    poseShadowLabel: 'Pose shadow',
    modelOpacityLabel: 'Model opacity',
    mirrorLabel: 'Mirror / flip',
    staticModeLabel: 'Static 2D mode',
    limbSelectionLabel: 'Body region selection',
    displayModesSectionTitle: 'Model display',
    overlaysSectionTitle: 'Overlays & helpers',
  },
};
