export const STRINGS = {
  tabs: {
    practice: 'Practice',
    library: 'Library',
    settings: 'Settings',
  },
  practice: {
    title: 'Practice',
    startPracticeButton: 'Start Practice',
    presetsSectionTitle: 'Presets',
  },
  library: {
    title: 'Library',
    openViewerButton: 'Open Viewer',
  },
  settings: {
    title: 'Settings',
  },
  viewer: {
    title: 'Viewer',
    timerLabel: 'Time remaining',
    play: 'Play',
    pause: 'Pause',
    skip: 'Skip',
    close: 'Close',
    directionalLight: 'Directional light',
    ambientLight: 'Ambient light',
  },
  common: {
    on: 'On',
    off: 'Off',
  },
  sessionConfig: {
    title: 'Session configuration',
    startSessionButton: 'Start session',
    savePresetButton: 'Save as preset',
    presetNameLabel: 'Preset name',
    presetsSectionTitle: 'Saved presets',
    subjectSectionTitle: 'Subject selection',
    displaySectionTitle: 'Display options',
    lightingSectionTitle: 'Lighting options',
    timeSectionTitle: 'Time options',
    categoryLabel: 'Pose categories',
    genderLabel: 'Gender',
    genderMale: 'Male',
    genderFemale: 'Female',
    genderBoth: 'Both',
    showGridLabel: 'Show ground grid',
    backgroundLabel: 'Background',
    backgroundDark: 'Dark',
    backgroundMid: 'Mid',
    backgroundLight: 'Light',
    directionalLightLabel: 'Directional light intensity',
    ambientLightLabel: 'Ambient light intensity',
    poseDurationLabel: 'Pose duration',
    poseCountLabel: 'Number of poses',
    breakDurationLabel: 'Break between poses',
    randomOrderLabel: 'Random order',
    durationSeconds: 'seconds',
    durationMinutes: 'minutes',
    posesSuffix: 'poses',
    breakOff: 'Off',
    breakSecondsSuffix: 's break',
  },
};

